[project]
name = "generative-ai-nd"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.2",
    "ipykernel>=7.1.0",
    "litellm>=1.80.10",
    "pip>=25.3",
    "unsloth>=2025.11.1",
]
